name: IK
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.3.4
  - ipympl=0.5.8
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jupyter_client=6.1.7
  - jupyter_contrib_core=0.3.3
  - jupyter_core=4.6.3
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2
  - nodejs=15.2.0
  - notebook=6.1.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - widgetsnbextension=3.5.1
